apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: sih24hqjp-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe:73bda097ec68d662bd9b30175f41fcf1fc3e49bf@sha256:2e231cb9914060a97459c59baa6bd7ee13d315f385805e9c920f647520ee5ee1
          name: container-image
